emr_config: null
features:
  override: false
features_defined:
  add_new_block_v2: true
  command_center: true
  compute_management: false
  custom_design: true
  data_integration_in_batch_pipeline: true
  dbt_v2: true
  display_local_timezone: true
  global_hooks: true
  interactions: true
  notebook_block_output_split_view: true
  operation_history: true
  polars: true
features_override: {}
help_improve_mage: true
latest_version: 0.9.72
name: unit_0_setup
openai_api_key: null
pipelines: null
platform_settings:
  emr_config: null
  features:
    override: false
  features_defined:
    add_new_block_v2: true
    command_center: true
    compute_management: false
    custom_design: true
    data_integration_in_batch_pipeline: true
    dbt_v2: true
    display_local_timezone: true
    global_hooks: true
    interactions: true
    notebook_block_output_split_view: true
    operation_history: true
    polars: true
  features_override: {}
  help_improve_mage: true
  latest_version: 0.9.72
  name: unit_0_setup
  openai_api_key: null
  pipelines: null
  platform_settings:
    projects:
      homework_3:
        path: homework_3
      unit_0_setup: {}
      unit_1_data_preparation: {}
      unit_2_training: {}
      unit_3_observability: {}
  project_uuid: 927108a7e6f24bf2aa636f01e6e96354
  projects:
    homework_3:
      path: homework_3
    unit_0_setup: {}
    unit_1_data_preparation: {}
    unit_2_training: {}
    unit_3_observability: {}
  remote_variables_dir: null
  repo_path: /home/src/mlops/unit_0_setup
  root_project: false
  settings:
    active: false
    uuid: unit_0_setup
  spark_config: null
  version: 0.9.71
  workspace_config_defaults: {}
project_uuid: 927108a7e6f24bf2aa636f01e6e96354
projects:
  homework_3:
    path: homework_3
  unit_0_setup: {}
  unit_1_data_preparation: {}
  unit_2_training: {}
  unit_3_observability: {}
remote_variables_dir: null
repo_path: /home/src/mlops/unit_0_setup
root_project: false
settings:
  active: false
  uuid: unit_0_setup
spark_config: null
version: 0.9.71
workspace_config_defaults: {}
